-- ============================================================
--  바이칼 휘트니스 서현점 — 공용 서버 준비
--  Supabase 대시보드 > SQL Editor 에 붙여넣고 Run 하면 끝입니다.
--  여러 번 실행해도 안전합니다.
-- ============================================================

-- ---------- 1. 표 만들기 -------------------------------------

-- 키 현황: 정상이 아닌 키만 담는다. 정상은 전체(407) - 여기 담긴 수.
create table if not exists public.keys (
  gender     text        not null check (gender in ('m', 'f')),
  no         int         not null check (no between 1 and 250),
  status     text        not null check (status in ('lost', 'broken', 'etc')),
  memo       text        not null default '',
  photos     text[]      not null default '{}',
  updated_at timestamptz not null default now(),
  primary key (gender, no)
);

-- 인수인계
create table if not exists public.handover (
  id        bigint      generated by default as identity primary key,
  body      text        not null default '',
  photos    text[]      not null default '{}',
  fav       boolean     not null default false,
  at        timestamptz not null default now(),
  edited_at timestamptz
);

-- 메모
create table if not exists public.memo (
  id        bigint      generated by default as identity primary key,
  body      text        not null default '',
  photos    text[]      not null default '{}',
  at        timestamptz not null default now(),
  edited_at timestamptz
);

-- 관리자에게 연락하기 게시판
create table if not exists public.posts (
  id     bigint      generated by default as identity primary key,
  body   text        not null default '',
  photos text[]      not null default '{}',
  at     timestamptz not null default now()
);

-- 목록을 최신순으로 자주 읽으니 색인을 둔다
create index if not exists handover_at_idx on public.handover (at desc);
create index if not exists memo_at_idx     on public.memo     (at desc);
create index if not exists posts_at_idx    on public.posts    (at desc);

-- ---------- 2. 접근 규칙 -------------------------------------
--  로그인 없이 누구나 읽고 쓰는 방식으로 정했다.
--  주소를 아는 사람은 누구나 읽고 쓰고 지울 수 있다.
--  나중에 잠그려면 아래 정책만 바꾸면 되고 앱 코드는 그대로다.

alter table public.keys     enable row level security;
alter table public.handover enable row level security;
alter table public.memo     enable row level security;
alter table public.posts    enable row level security;

drop policy if exists open_keys     on public.keys;
drop policy if exists open_handover on public.handover;
drop policy if exists open_memo     on public.memo;
drop policy if exists open_posts    on public.posts;

create policy open_keys     on public.keys     for all to anon using (true) with check (true);
create policy open_handover on public.handover for all to anon using (true) with check (true);
create policy open_memo     on public.memo     for all to anon using (true) with check (true);
create policy open_posts    on public.posts    for all to anon using (true) with check (true);

-- ---------- 3. 사진 저장소 -----------------------------------

insert into storage.buckets (id, name, public)
values ('photos', 'photos', true)
on conflict (id) do update set public = true;

drop policy if exists photos_read   on storage.objects;
drop policy if exists photos_write  on storage.objects;
drop policy if exists photos_delete on storage.objects;

create policy photos_read   on storage.objects for select to anon using (bucket_id = 'photos');
create policy photos_write  on storage.objects for insert to anon with check (bucket_id = 'photos');
create policy photos_delete on storage.objects for delete to anon using (bucket_id = 'photos');
